var express = require('express');
var router = express.Router();
//below autogenerated routes
router.get('/', function (req, res) {
  res.render('rendered/locura', { title: 'locura' });
});

module.exports = router;
