var express = require('express');
var router = express.Router();
var SDB = require('../models/db');
//below autogenerated routes
router.get('/', function (req, res) {
  res.render('rendered/index', { title: 'Index' });
});

router.get("/createTables", function(req, res){
 SDB.createTables();
 res.end();
});

module.exports = router;
